package schedule

import (
	"context"
	"fmt"
	"sync/atomic"
	"xgc-agent/utils"
)

type NodeType int32

const (
	NodeTypeNormal NodeType = iota
	NodeTypeConditional
	NodeTypeSubGraph
	_NodeTypeConditionalVirtual
)

var NodeTypeSlice = []NodeType{NodeTypeNormal, NodeTypeConditional}

type INode interface {
	Execute(ctx context.Context, state *GraphState) (err error)
}

type Node struct {
	Name string
	Type NodeType
	// Fn is the function to execute for this node.
	Fn INode
	// State represents the current execution state of the node, which can be one of the following:
	// - NodePending: the node is waiting to be executed.
	// - NodeRunning: the node is currently being executed.
	// - NodeSkipped: the node was skipped due to a conditional check.
	// - NodeFinished: the node has finished executing successfully.
	// - NodeFailed: the node has finished executing with an error.
	State int32
	Prev  []*Node
	Next  []*Node // Next nodes to execute after this node

	// id is the unique identifier of the node, generated by the scheduler
	id int32
}

func (n *Node) Execute(ctx context.Context, state *GraphState) {
	if n.Type == NodeTypeConditional {
		n.executeConditional(ctx, state)
		return
	} else if n.Type == _NodeTypeConditionalVirtual {
		return
	}

	if err := n.Fn.Execute(ctx, state); err != nil {
		n.setState(NodeFailed)
		state.err <- fmt.Errorf("node %s execution failed, err %v", n.Name, err)
		return
	}

	n.setState(NodeFinished)
	state.done <- n
	return
}

func (n *Node) executeConditional(ctx context.Context, state *GraphState) {
	if err := n.Fn.Execute(ctx, state); err != nil {
		n.setState(NodeFailed)
		state.err <- err
		return
	}

	value, ok := state.Context.Get(fmt.Sprintf("__condition_%d_result__", n.id))
	if !ok {
		n.setState(NodeFailed)
		state.err <- fmt.Errorf("conditional node %s did not set condition result", n.Name)
		return
	}

	n.setState(NodeFinished)

	tags, _ := value.([]string)
	for _, next := range n.Next {
		if utils.SliceContains(tags, next.Name) {
			next.setState(NodeFinished)
		} else {
			next.setState(NodeSkipped)
		}
		state.done <- next
	}

	return
}

func (n *Node) setState(state int32) {
	atomic.StoreInt32(&n.State, state)
}
