package message

import (
	"encoding/json"
	"xgc-agent/tools"
)

// Role represents the role of a message sender.
type Role string

// Error type constants for ResponseError.Type field.
const (
	ErrorTypeStreamError  = "stream_error"
	ErrorTypeAPIError     = "api_error"
	ErrorTypeFlowError    = "flow_error"
	ErrorTypeRunError     = "run_error"
	ErrorTypeNoResponding = "no_responding"
)

// Role constants for different message senders.
const (
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleTool      Role = "tool"
)

// ContentType represents the type of content.
type ContentType string

// ContentType constants for content types.
const (
	ContentTypeText  ContentType = "text"
	ContentTypeImage ContentType = "image"
	ContentTypeAudio ContentType = "audio"
	ContentTypeVideo ContentType = "video"
	ContentTypeFile  ContentType = "file"
)

// ContentPart represents a single part in a multi-modal content.
type ContentPart struct {
	Type  ContentType `json:"type"`
	Text  *string     `json:"text,omitempty"`
	Image *Image      `json:"image,omitempty"`
	Audio *Audio      `json:"audio,omitempty"`
	Video *Video      `json:"video,omitempty"`
	File  *File       `json:"file,omitempty"`
}

// Image represents an image content part for vision-capable models.
type Image struct {
	// URL is the URL of the image.
	URL string `json:"url"`
	// Data is the binary content of the image.
	Data []byte `json:"data,omitempty"`
	// AltText is the alternative text for the image.
	AltText string `json:"alt_text,omitempty"`
	// Detail is the detail level: "low", "high", "auto".
	Detail string `json:"detail,omitempty"`
	// Format is the format of the image.
	Format string `json:"format,omitempty"`
}

// Audio represents an audio content part for audio-capable models.
type Audio struct {
	// URL is the URL of the audio file.
	URL string `json:"url"`
	// Data is the binary content of the audio.
	Data []byte `json:"data,omitempty"`
	// Format is the format of the audio file.
	Format string `json:"format,omitempty"`
	// Duration is the duration of the audio in seconds.
	Duration float32 `json:"duration,omitempty"`
}

// Video represents a video content part for video-capable models.
type Video struct {
	// URL is the URL of the video file.
	URL string `json:"url"`
	// Data is the binary content of the video.
	Data []byte `json:"data,omitempty"`
	// Format is the format of the video file.
	Format string `json:"format,omitempty"`
	// Duration is the duration of the video in seconds.
	Duration float32 `json:"duration,omitempty"`
}

// File represents a file content part for file-capable models.
type File struct {
	// Filename is the name of the file.Used when uploading files to the model.
	Filename string `json:"filename"`
	// Data is the binary content of the file.
	Data []byte `json:"data"`
	// FileID is the identifier of the file when referencing an existing file.
	FileID string `json:"file_id,omitempty"`
	// MimeType is the format of the file.
	MimeType string `json:"format,omitempty"`
}

// Messages represents a single message in a chat conversation.
type Messages struct {
	// Role of the message sender
	Role Role `json:"role"`
	// Content of the message
	Content      string        `json:"content"`
	ContentParts []ContentPart `json:"content_parts,omitempty"`
	// ToolCalls are tool call requests emitted by the assistant.
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	// ToolID associates a tool response message with a tool call.
	ToolID string `json:"tool_call_id,omitempty"`
	// ToolName is the name of the tool used in a tool response message.
	ToolName string `json:"tool_name,omitempty"`
}

// NewMessage creates a new message with the given role and content. (helper function)
func NewMessage(role Role, content string) Messages {
	return Messages{
		Role:    role,
		Content: content,
	}
}

// MessageUser creates a user message with the given content.
// user messages represent inputs from the end-user.
func MessageUser(content string) Messages {
	return Messages{
		Role:    RoleUser,
		Content: content,
	}
}

// MessageSystem creates a system message with the given content.
// system messages provide instructions or context to the model.
// they are not visible to the end-user.
func MessageSystem(content string) Messages {
	return Messages{
		Role:    RoleSystem,
		Content: content,
	}
}

// MessageAssistant creates an assistant message with the given content.
// assistant messages represent responses generated by the model.
// they can also include tool call requests.
func MessageAssistant(content string) Messages {
	return Messages{
		Role:    RoleAssistant,
		Content: content,
	}
}

// MessageTool creates a tool message with the given content.
// tool messages represent responses from external tools invoked by the model.
func MessageTool(toolID, toolName, content string) Messages {
	// TODO: add tool name field later
	return Messages{
		Role:     RoleTool,
		Content:  content,
		ToolID:   toolID,
		ToolName: toolName,
	}
}

// ToolCall represents a tool invocation requested by the model in a message.
type ToolCall struct {
	// the unique identifier of the tool call
	ID string `json:"id,omitempty"`
	// The tool message to be called.
	ToolDefinition ToolDefinition `json:"tool_definition"`
	// Index is used to indicate the order of tool calls in a message.
	// In streaming scenarios, it is used to identify identify the chunk of the tool call for merging.
	Index *int `json:"index,omitempty"`
	// Extra information for the tool call.
	Extra map[string]any `json:"extra,omitempty"`
}

// ToolDefinition describes a tool exposed to the model.
// Parameters should be a JSON Schema object.
type ToolDefinition struct {
	// The type of the tool, e.g., "streaming" or "non-streaming".
	Type        tools.ToolType  `json:"type,omitempty"`
	Name        string          `json:"name"`
	Description string          `json:"description,omitempty"`
	Parameters  json.RawMessage `json:"parameters,omitempty"`
}

// ToolChoice controls how the model chooses tools.
// Type can be: "auto", "none", or "tool" (with Name).
type ToolChoice struct {
	Type string `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
}

// StreamEvent is emitted during streaming.
type StreamEvent struct {
	Delta string
	Done  bool
	// Raw is the raw provider event bytes (best-effort). It can be nil.
	Raw []byte
	// ToolCalls are tool invocations emitted during streaming (best-effort).
	ToolCalls []ToolCall
}
